config/routes.rb
Rails.application.routes.draw do
  resources :cocktails, only: [:index, :show, :new, :edit, :update, :create] do
    resources :doses, only: [:new, :create]
  end
  resources :doses, only: [:destroy]

  get 'cocktail/mixologist', to: 'cocktails#mixologist', as: 'mixologist_path'

  root "cocktails#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, uniqueness: true, presence: true
  mount_uploader :photo, PhotoUploader
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: true
  validates_uniqueness_of :ingredient_id, scope: [:cocktail_id]
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses, dependent: :destroy
  validates :name, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
require 'faker'

class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def edit
    @cocktail = Cocktail.find(params[:id])
  end

  def update
    @cocktail = Cocktail.find(params[:id])
    @cocktail.update(cocktail_params)

    redirect_to cocktail_path(@cocktail)
  end

  def destroy
    @cocktail = Cocktail.find(params[:id])
    @cocktail.destroy
    redirect_to cocktails_path
  end


  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end

   def set_ingredient_range
    (Ingredient.first.id..Ingredient.last.id)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController

  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def create
    @dose = Dose.new(dose_params)
    @dose.cocktail = Cocktail.find(params[:cocktail_id])
    if @dose.save
      redirect_to cocktail_path(@dose.cocktail)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktails_path
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cocktails/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <h2> Edit Cocktail</h2>
      <%= simple_form_for [@cocktail] do |f| %>
        <%= f.input :name %>
        <%= f.input :photo %>
        <%= f.input :photo_cache, as: :hidden %>
        <%= f.submit class: "btn btn-yours" %>
      <% end %>
    </div>
  </div>
</div>

app/views/cocktails/index.html.erb
<% content_for(:banner) do %>
<%= render 'shared/banner' %>
<% end %>

<div id="content-under" class="container">
  <div class="row">
    <% @cocktails.each do |c| %>
    <div class="col-xs-12 col-sm-4">
      <div class="card">
       <div class="card-body" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path c.photo unless c.photo.blank?%>');">
        <div class="card-description">
            <h2><%= link_to c.name, cocktail_path(c) %></h2>
          </div>
          <%= link_to "", cocktail_path(c), class: "card-link"  %>
        <div class="card-footer">
          <div class="card-date">
            <% doses = Dose.where(cocktail_id: c.id)  %>
            <p><%= doses.count %> Ingredients </p>
          </div>
        </div>
       </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/cocktails/mixologist.html.erb
<div class="container">
  <h1> The Mixologist's creation</h1>
  <div class="row">
    <div class="col-xs-12">
      <div class="card cocktail-card">
        <h3 class="cocktail-title">Your cocktail is the <%= @cocktail.name %></h3>
        <%= link_to 'Edit cocktail', edit_cocktail_path(@cocktail), class: "btn btn-yours btn-top-right" %>
        <%= link_to 'Add dose', new_cocktail_dose_path(@cocktail), class: "btn btn-yours btn-top-right-two" %>
        <h4 class="cocktail-title"> Doses </h4>
        <% doses = Dose.where(cocktail_id: @cocktail.id)  %>
        <ul class="cocktail-title doses-list">
          <% doses.each do |d| %>
            <li> <%= d.description %> de <%= d.ingredient.name %> <%= link_to '<i class="fa fa-trash-o" aria-hidden="true"></i>'.html_safe, dose_path(d), method: :delete, data: { confirm: "Are you sure?" }%></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
  <%#= button_to 'Add review', new_cocktail_review_path(@cocktail), :method => "get", class: "btn btn-primary" %>
</div>

app/views/cocktails/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <h2> New Cocktail</h2>
      <%= simple_form_for [@cocktail] do |f| %>
        <%= f.input :name %>
        <%= f.input :photo %>
        <%= f.input :photo_cache, as: :hidden %>
        <%= f.submit class: "btn btn-yours" %>
      <% end %>
    </div>
  </div>
</div>

<%= link_to 'New Cocktail', new_cocktail_path %>

app/views/cocktails/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <div class="card cocktail-card">
        <h3 class="cocktail-title"><%= @cocktail.name %></h3>
        <%= link_to 'Edit cocktail', edit_cocktail_path(@cocktail), class: "btn btn-yours btn-top-right" %>
        <%= link_to 'Add dose', new_cocktail_dose_path(@cocktail), class: "btn btn-yours btn-top-right-two" %>
        <%= image_tag "longisland.jpg", height: 300, width: 400, crop: :fill %>
        <h4 class="cocktail-title"> Doses </h4>
        <% doses = Dose.where(cocktail_id: @cocktail.id)  %>
        <ul class="cocktail-title doses-list">
          <% doses.each do |d| %>
            <li> <%= d.description %> of <%= d.ingredient.name %> <%= link_to '<i class="fa fa-trash-o" aria-hidden="true"></i>'.html_safe, dose_path(d), method: :delete, data: { confirm: "Are you sure?" }%></li>
          <% end %>

        </ul>
      </div>
    </div>
  </div>
  <%#= button_to 'Add review', new_cocktail_review_path(@cocktail), :method => "get", class: "btn btn-primary" %>
</div>

app/views/doses/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <%= simple_form_for [@cocktail, @dose] do |f| %>
        <%= f.input :description, label: 'How do you want to add it?' %>
        <%= f.association :ingredient, label: 'Pick an ingredient' %>
        <%= f.submit "Add Dose!!", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if content_for?(:banner) %>
      <%= yield(:banner) %>
      <%= yield %>
    <% else %>
      <%= render 'shared/navbar' %>
      <%= yield %>
    <% end %>
    <%= render 'shared/footer' %>
    <%= javascript_include_tag "application" %>
    <%= javascript_pack_tag "application" %>
  </body>
</html>

app/views/shared/_banner.html.erb
<div class="banner">
  <div class="banner-content">
    <h1>The AI powered Mixologist<span class="sup">®</span></h1>
    <p>
      <span id="banner-typed-text"></span>
    </p>
    <%= link_to "Start", 'cocktail/mixologist', class: " btn btn-banner" %>
  </div>
</div>

<div class="navbar-t navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
  <%= image_tag "logo.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Links -->
    <%= link_to "Home", root_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <%= link_to "New Cocktail", new_cocktail_path, class: " btn btn-yours" %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><%= link_to "Home", root_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
        <li><%= link_to "New Cocktail", new_cocktail_path, class: " btn btn-yours" %></li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fas fa-github"></i></a>
    <a href="#"><i class="fas fa-twitter"></i></a>
    <a href="#"><i class="fas fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This website is made with <i class="fa fa-heart"></i> by <span class="nice-underline">Edouard</span>
  </div>
</div>

app/views/shared/_navbar.html.erb
 <div class="navbar-wagon navbar-fixed-top">
    <!-- Logo -->
    <%= link_to root_path, class: "navbar-wagon-brand" do %>
      <%= image_tag "logo.png" %>
    <% end %>

    <!-- Right Navigation -->
    <div class="navbar-wagon-right hidden-xs hidden-sm">

      <!-- Links -->
      <%= link_to "Home", root_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "New Cocktail", new_cocktail_path, class: " btn btn-yours" %>
    </div>

    <!-- Dropdown list appearing on mobile only -->
    <div class="navbar-wagon-item hidden-md hidden-lg">
      <div class="dropdown">
        <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><a href="#">Some mobile link</a></li>
          <li><a href="#">Other one</a></li>
          <li><a href="#">Other one</a></li>
        </ul>
      </div>
    </div>
  </div>